spool createDBN0UsersRoles_AltaiaMediation_DBN0_ERI_RAN_SCHEMA.log
PROMPT
PROMPT Executar no schema SYSTEM
PROMPT
PROMPT '[ENTER] PARA INICIAR A INSTALACAO'
PAUSE
PROMPT
SET DEFINE ON;
CREATE USER DBN0_ERI_RAN
	IDENTIFIED BY DBN0_ERI_RAN
	DEFAULT TABLESPACE DBN0_T
	TEMPORARY TABLESPACE TEMP
	PROFILE DEFAULT
	ACCOUNT UNLOCK;
	-- Roles for DBN0_ERI_RAN 
	GRANT PRIVS_GESTOR TO DBN0_ERI_RAN;
	GRANT CONNECT TO DBN0_ERI_RAN;
	GRANT ALTER ANY CUBE TO DBN0_ERI_RAN;
	GRANT ALTER SESSION TO DBN0_ERI_RAN;
	GRANT CREATE JOB TO DBN0_ERI_RAN;
	GRANT CREATE PROCEDURE TO DBN0_ERI_RAN;
	GRANT CREATE SEQUENCE TO DBN0_ERI_RAN;
	GRANT CREATE SESSION TO DBN0_ERI_RAN;
	GRANT CREATE SYNONYM TO DBN0_ERI_RAN;
	GRANT CREATE TABLE TO DBN0_ERI_RAN;
	GRANT CREATE TYPE TO DBN0_ERI_RAN;
	GRANT CREATE VIEW TO DBN0_ERI_RAN;
	GRANT CREATE TRIGGER TO DBN0_ERI_RAN;
	ALTER USER DBN0_ERI_RAN DEFAULT ROLE ALL;
	-- 2 Tablespace Quotas for DBN0_ERI_RAN
	ALTER USER DBN0_ERI_RAN QUOTA UNLIMITED ON DBN0_I;
	ALTER USER DBN0_ERI_RAN QUOTA UNLIMITED ON DBN0_T;
SET DEFINE OFF;
spool off
