--liquibase formatted sql
--changeset namf:namf-ERICSSON_OSS_RAN_EBS_5G-liq_00_createSchema_DBN0_ERI_RAN-20250929231211
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(1) FROM all_users WHERE username = UPPER('DBN0_ERI_RAN');

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER DBN0_ERI_RAN IDENTIFIED BY DBN0_ERI_RAN
    DEFAULT TABLESPACE DBN0_T
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
    ACCOUNT UNLOCK';
  EXECUTE IMMEDIATE 'GRANT PRIVS_GESTOR TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CONNECT TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT ALTER ANY CUBE TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE JOB TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO DBN0_ERI_RAN';
  EXECUTE IMMEDIATE 'ALTER USER DBN0_ERI_RAN DEFAULT ROLE ALL';
  EXECUTE IMMEDIATE 'ALTER USER DBN0_ERI_RAN QUOTA UNLIMITED ON DBN0_I';
  EXECUTE IMMEDIATE 'ALTER USER DBN0_ERI_RAN QUOTA UNLIMITED ON DBN0_T';
END;
/
