DO $$
DECLARE
	DBN0T VARCHAR(255);
	PARTITION_INITIAL_DAY VARCHAR(255);
	PARTITION_NAME_DAY VARCHAR(255);
	PARTITION_VALUE_DAY VARCHAR(255);
	PARTITION_NAME_NEXTDAY VARCHAR(255);
	PARTITION_VALUE_NEXTDAY VARCHAR(255);
	
BEGIN
	RAISE NOTICE '%', '==================== DBN0 Table creation ====================';

	-- Partition names
	SELECT INTO DBN0T 'dbn0_t';
	SELECT INTO PARTITION_NAME_DAY 'P_'||TO_CHAR(clock_timestamp(),'YYYYMMDD');
	SELECT INTO PARTITION_VALUE_DAY TO_CHAR(clock_timestamp() + INTERVAL '1 DAY', 'YYYY-MM-DD 00:00:00');
	SELECT INTO PARTITION_INITIAL_DAY 0;
	SELECT INTO PARTITION_NAME_NEXTDAY 'P_'||TO_CHAR(clock_timestamp() + INTERVAL '15 YEAR','YYYYMMDD');
	SELECT INTO PARTITION_VALUE_NEXTDAY TO_CHAR(clock_timestamp() + INTERVAL '15 YEAR', 'YYYY-MM-DD 00:00:00');

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_EP_NGU_%s PARTITION OF DBN0_ERI_RAN.EBS_EP_NGU FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_EP_NGU_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_EP_NGU_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_EP_NGU_1_%s PARTITION OF DBN0_ERI_RAN.EBS_EP_NGU_1 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_1_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_EP_NGU_1_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_EP_NGU_1_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_1_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_EP_NGU_0_%s PARTITION OF DBN0_ERI_RAN.EBS_EP_NGU_0 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_0_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_EP_NGU_0_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_EP_NGU_0_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_0_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_EP_NGU_2_%s PARTITION OF DBN0_ERI_RAN.EBS_EP_NGU_2 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_2_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_EP_NGU_2_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_EP_NGU_2_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EP_NGU_2_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_EUTRANCELLRELATION_%s PARTITION OF DBN0_ERI_RAN.EBS_EUTRANCELLRELATION FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EUTRANCELLRELATION_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_EUTRANCELLRELATION_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_EUTRANCELLRELATION_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_EUTRANCELLRELATION_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_%s PARTITION OF DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_RESULT_%s PARTITION OF DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_RESULT FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_RESULT_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_RESULT_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_RESULT_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUCPFUNCTION_RESULT_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_%s PARTITION OF DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_TRIGGER_%s PARTITION OF DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_TRIGGER FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_TRIGGER_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_TRIGGER_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_TRIGGER_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBCUUPFUNCTION_TRIGGER_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_GNBDUFUNCTION_%s PARTITION OF DBN0_ERI_RAN.EBS_GNBDUFUNCTION FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBDUFUNCTION_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_GNBDUFUNCTION_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_GNBDUFUNCTION_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_GNBDUFUNCTION_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPNGCAUS_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPNGCAUS FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPNGCAUS_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPNGCAUS_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPNGCAUS_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPNGCAUS_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPX2CAUS_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPX2CAUS FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPX2CAUS_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPX2CAUS_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPX2CAUS_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPX2CAUS_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPXNCAUS_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPXNCAUS FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPXNCAUS_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPXNCAUS_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPXNCAUS_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSEGRPXNCAUS_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_TRIGGER_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_TRIGGER FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_TRIGGER_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_TRIGGER_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_TRIGGER_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_TRIGGER_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_REASON_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_REASON FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_REASON_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_REASON_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_REASON_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_REASON_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_TYPE_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_TYPE FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_TYPE_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_TYPE_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_TYPE_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_TYPE_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_RESULT_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_RESULT FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_RESULT_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_RESULT_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_RESULT_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_RESULT_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_CAUSE_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_CAUSE FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSE_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSE_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_CAUSE_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_CAUSE_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_CAUSEGRPF1CAUS_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_CAUSEGRPF1CAUS FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_CAUSEGRPF1CAUS_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_CAUSEGRPF1CAUS_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_CAUSEGRPF1CAUS_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_CAUSEGRPF1CAUS_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_RESULT_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_RESULT FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_RESULT_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_RESULT_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_RESULT_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_RESULT_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLRELATION_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLRELATION FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLRELATION_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLRELATION_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLRELATION_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLRELATION_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_PPCONTROLLINK_%s PARTITION OF DBN0_ERI_RAN.EBS_PPCONTROLLINK FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_PPCONTROLLINK_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_PPCONTROLLINK_0_%s PARTITION OF DBN0_ERI_RAN.EBS_PPCONTROLLINK_0 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_0_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_0_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_PPCONTROLLINK_0_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_0_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_PPCONTROLLINK_1_%s PARTITION OF DBN0_ERI_RAN.EBS_PPCONTROLLINK_1 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_1_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_1_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_PPCONTROLLINK_1_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_PPCONTROLLINK_1_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_13_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_13 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_13_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_13_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_13_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_13_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_34_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_34 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_34_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_34_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_34_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_34_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_18_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_18 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_18_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_18_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_18_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_18_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_20_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_20 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_20_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_20_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_20_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_20_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_6_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_6 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_6_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_6_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_6_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_6_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_15_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_15 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_15_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_15_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_15_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_15_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_16_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_16 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_16_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_16_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_16_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_16_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_23_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_23 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_23_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_23_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_23_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_23_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_25_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_25 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_25_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_25_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_25_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_25_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_17_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_17 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_17_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_17_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_17_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_17_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_14_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_14 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_14_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_14_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_14_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_14_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_3_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_3 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_3_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_3_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_3_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_3_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_31_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_31 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_31_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_31_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_31_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_31_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_4_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_4 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_4_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_4_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_4_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_4_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_2_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_2 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_2_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_2_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_2_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_2_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_27_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_27 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_27_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_27_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_27_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_27_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_8_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_8 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_8_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_8_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_8_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_8_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_11_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_11 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_11_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_11_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_11_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_11_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_19_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_19 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_19_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_19_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_19_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_19_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_21_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_21 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_21_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_21_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_21_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_21_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_32_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_32 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_32_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_32_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_32_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_32_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_30_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_30 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_30_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_30_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_30_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_30_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_22_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_22 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_22_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_22_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_22_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_22_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_12_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_12 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_12_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_12_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_12_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_12_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_24_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_24 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_24_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_24_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_24_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_24_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_10_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_10 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_10_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_10_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_10_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_10_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_26_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_26 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_26_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_26_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_26_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_26_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_1_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_1 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_1_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_1_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_1_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_1_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_28_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_28 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_28_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_28_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_28_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_28_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_9_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_9 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_9_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_9_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_9_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_9_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_33_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_33 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_33_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_33_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_33_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_33_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_5_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_5 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_5_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_5_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_5_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_5_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_7_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_7 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_7_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_7_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_7_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_7_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_0_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_0 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_0_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_0_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_0_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_0_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_RPUSERPLANELINK_29_%s PARTITION OF DBN0_ERI_RAN.EBS_RPUSERPLANELINK_29 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_29_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_29_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_RPUSERPLANELINK_29_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_RPUSERPLANELINK_29_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_S1ULINK_%s PARTITION OF DBN0_ERI_RAN.EBS_S1ULINK FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_S1ULINK_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_S1ULINK_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_S1ULINK_1_%s PARTITION OF DBN0_ERI_RAN.EBS_S1ULINK_1 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_1_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_S1ULINK_1_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_S1ULINK_1_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_1_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_S1ULINK_0_%s PARTITION OF DBN0_ERI_RAN.EBS_S1ULINK_0 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_0_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_S1ULINK_0_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_S1ULINK_0_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_0_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_S1ULINK_2_%s PARTITION OF DBN0_ERI_RAN.EBS_S1ULINK_2 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_2_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_S1ULINK_2_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_S1ULINK_2_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_S1ULINK_2_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_SLC_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_SLC FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_SLC_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_SLC_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_SLC_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_SLC_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_SLC_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_SLC FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_SLC_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_SLC_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_SLC_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_SLC_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_4_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_4 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_4_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_4_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_4_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_4_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_22_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_22 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_22_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_22_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_22_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_22_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_5_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_5 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_5_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_5_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_5_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_5_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_19_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_19 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_19_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_19_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_19_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_19_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_36_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_36 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_36_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_36_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_36_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_36_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_7_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_7 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_7_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_7_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_7_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_7_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_33_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_33 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_33_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_33_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_33_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_33_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_13_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_13 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_13_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_13_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_13_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_13_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_17_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_17 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_17_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_17_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_17_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_17_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_31_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_31 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_31_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_31_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_31_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_31_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_28_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_28 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_28_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_28_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_28_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_28_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_6_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_6 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_6_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_6_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_6_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_6_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_16_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_16 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_16_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_16_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_16_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_16_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_37_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_37 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_37_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_37_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_37_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_37_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_1_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_1 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_1_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_1_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_1_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_1_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_10_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_10 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_10_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_10_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_10_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_10_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_12_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_12 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_12_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_12_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_12_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_12_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_38_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_38 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_38_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_38_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_38_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_38_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_49_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_49 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_49_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_49_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_49_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_49_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_15_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_15 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_15_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_15_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_15_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_15_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_27_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_27 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_27_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_27_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_27_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_27_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_25_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_25 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_25_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_25_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_25_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_25_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_20_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_20 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_20_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_20_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_20_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_20_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLDU_35_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLDU_35 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_35_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLDU_35_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLDU_35_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLDU_35_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_70_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_70 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_70_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_70_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_70_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_70_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_67_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_67 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_67_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_67_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_67_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_67_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_90_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_90 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_90_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_90_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_90_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_90_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_93_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_93 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_93_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_93_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_93_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_93_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_28_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_28 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_28_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_28_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_28_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_28_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_87_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_87 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_87_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_87_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_87_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_87_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_55_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_55 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_55_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_55_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_55_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_55_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_63_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_63 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_63_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_63_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_63_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_63_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_42_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_42 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_42_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_42_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_42_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_42_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_53_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_53 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_53_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_53_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_53_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_53_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_78_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_78 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_78_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_78_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_78_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_78_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_102_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_102 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_102_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_102_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_102_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_102_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_101_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_101 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_101_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_101_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_101_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_101_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_31_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_31 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_31_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_31_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_31_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_31_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_96_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_96 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_96_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_96_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_96_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_96_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_103_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_103 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_103_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_103_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_103_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_103_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_60_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_60 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_60_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_60_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_60_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_60_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_99_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_99 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_99_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_99_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_99_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_99_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_39_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_39 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_39_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_39_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_39_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_39_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_33_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_33 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_33_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_33_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_33_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_33_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_49_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_49 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_49_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_49_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_49_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_49_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_75_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_75 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_75_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_75_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_75_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_75_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_65_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_65 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_65_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_65_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_65_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_65_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_30_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_30 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_30_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_30_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_30_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_30_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_48_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_48 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_48_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_48_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_48_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_48_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_43_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_43 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_43_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_43_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_43_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_43_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_5_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_5 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_5_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_5_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_5_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_5_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_17_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_17 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_17_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_17_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_17_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_17_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_4_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_4 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_4_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_4_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_4_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_4_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_0_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_0 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_0_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_0_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_0_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_0_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_21_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_21 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_21_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_21_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_21_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_21_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_3_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_3 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_3_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_3_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_3_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_3_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_19_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_19 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_19_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_19_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_19_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_19_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_12_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_12 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_12_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_12_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_12_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_12_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_18_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_18 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_18_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_18_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_18_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_18_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	EXECUTE format('CREATE TABLE IF NOT EXISTS DBN0_ERI_RAN.EBS_NRCELLCU_14_%s PARTITION OF DBN0_ERI_RAN.EBS_NRCELLCU_14 FOR VALUES FROM (to_timestamp(%s)) TO (''%s'');', PARTITION_NAME_NEXTDAY, PARTITION_INITIAL_DAY, PARTITION_VALUE_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_14_%s OWNER to DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('GRANT ALL ON TABLE DBN0_ERI_RAN.EBS_NRCELLCU_14_%s TO DBN0_ERI_RAN;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('REVOKE ALL ON DBN0_ERI_RAN.EBS_NRCELLCU_14_%s FROM postgres;', PARTITION_NAME_NEXTDAY);
	EXECUTE format('ALTER TABLE DBN0_ERI_RAN.EBS_NRCELLCU_14_%s SET TABLESPACE %s;', PARTITION_NAME_NEXTDAY, DBN0T);

	RAISE NOTICE '%', '=============== DBN0 Table creation completed ===============';

	COMMIT;
END $$;